name: Java Maven Deployment with Security Group Update

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Get GitHub Runner's Public IP
      - name: Get GitHub Runner IP
        id: get_ip
        run: echo "runner_ip=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_ENV

      # Update AWS Security Group
      - name: Add GitHub Runner IP to Security Group
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          runner_ip=${{ env.runner_ip }}
          security_group_id=${{ secrets.AWS_SECURITY_GROUP_ID }}
          echo "Adding runner IP $runner_ip to Security Group $security_group_id"
          aws ec2 authorize-security-group-ingress \
            --group-id $security_group_id \
            --protocol tcp \
            --port 22 \
            --cidr $runner_ip/32

      # Add SSH key for appleboy/ssh-action
      - name: Set up SSH Agent
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.AWS_SERVER_HOST }}
          username: ${{ secrets.AWS_SERVER_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22

      # Copy repository files to the server
      - name: Copy Files to Server
        uses: appleboy/scp-action@v0.1.3
        with:
          source: "."
          target: "/home/${{ secrets.AWS_SERVER_USER }}/java-app"
          host: ${{ secrets.AWS_SERVER_HOST }}
          username: ${{ secrets.AWS_SERVER_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22

      # Run deployment commands on the server
      - name: Deploy Java Maven App
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.AWS_SERVER_HOST }}
          username: ${{ secrets.AWS_SERVER_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.AWS_SERVER_USER }}/java-app
            mvn clean install
            nohup java -jar target/*.jar &
      
      # Clean up Security Group Rules
      - name: Remove GitHub Runner IP from Security Group
        
        run: |
          runner_ip=${{ env.runner_ip }}
          security_group_id=${{ secrets.AWS_SECURITY_GROUP_ID }}
          echo "Removing runner IP $runner_ip from Security Group $security_group_id"
          aws ec2 revoke-security-group-ingress \
            --group-id $security_group_id \
            --protocol tcp \
            --port 22 \
            --cidr $runner_ip/32
