name: Deploy Maven Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn package

    - name: Configure AWS Security Group for Runner
      run: |
        INSTANCE_IP=$(curl -s http://checkip.amazonaws.com)
        aws ec2 authorize-security-group-ingress \
          --group-id <SECURITY_GROUP_ID> \
          --protocol tcp \
          --port 22 \
          --cidr $INSTANCE_IP/32 \
          --region ${{ secrets.AWS_REGION }}

    - name: Deploy WAR/JAR to EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk 
          wget https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
          sudo tar xzf apache-maven-3.9.5-bin.tar.gz -C /opt
          sudo rm -f /usr/bin/mvn
          sudo ln -s /opt/apache-maven-3.9.5/bin/mvn /usr/bin/mvn
          mvn -version
          sudo apt install -y tomcat9
          if [ -f target/*.war ]; then
            sudo cp target/*.war /var/lib/tomcat9/webapps/
            sudo systemctl restart tomcat9
          elif [ -f target/*.jar ]; then
            nohup java -jar target/*.jar > app.log 2>&1 &
          fi
